name: build

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: publish to registry
        run: docker build .
