name: gesto-front

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: publish to registry
        uses: VaultVulp/gp-docker-action@1.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          image-name: gesto-front

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: SSH Execute Commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 2024
          script: |
            echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            docker stop gesto-front
            docker rm gesto-front
            docker image rm -f ghcr.io/gesto-team/gesto-front/gesto-front
            docker run -d -p 8080:80 -v /etc/nginx/sites-available/gesto-docker-front.conf:/etc/nginx/conf.d/default.conf  --name gesto-front ghcr.io/gesto-team/gesto-front/gesto-front
